print("*****************reading file***************")
file=open("sample.txt",'r')
print(file.read())
print("*****************reading file with state ment***************")
with open("sample.txt") as file:
    data=file.read()
    print(data)
print("*****************reading file with for loop***************")
file=open("sample.txt",'r')
for a in file:
    print(a)
print("*****************to read a certain value***************")
file=open("sample.txt",'r')
print(file.read(145))
print("*****************to read line***************")
f=open("sample.txt",'r')
print(f.readline(3))
f.seek(0)
print(f.readlines())
f.close()
